# Generated by Django 4.1 on 2022-10-21 02:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppDoku', '0002_remove_mijuego_fecha_mijuego_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mijuego',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
